yandex:
  url: https://taxi-routeinfo.taxi.yandex.net/taxi_info
  clid: ak240329
  apiKey: SScSAOuJwVTHpFyPETbOkvpmDUDCEDrAubHwJT

coordinate:
  start-longitude: 27.596461
  start-latitude: 53.930974
  finish-longitude: 27.592652
  finish-latitude: 53.919208
  relative-length: 1370

spring:
  data:
    redis:
      port: 6279
      host: localhost

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true


